### PR TITLE
Stepper functions

### PR DESCRIPTION
**Pull request by kg7ski**
Tamas,

This is all new to me, but I think I have done it correctly.  I am not sure about the documentation file. Please let me know what I can do better.

cheers,

ski

### CODE REVIEW

**Comment by kg7ski** [comment]
Ok, I updated it to not need a separate step-continue function and added the stepper functions to the menu items.

**Comment by kovisoft** [comment]
Thank you for the contribution (and sorry for the delay, I'm quite busy these days). I have some comments on this pull request:

(1) It seems to me that something is missing from your second commit. It says that "_Better implementation of continue so we can use ,n to continue in the stepper and I added the stepper code to the menu options_". However I see only changes in `slimv.txt`. Did you commit all of your changes?

(2) I also tested your new functions with a lisp implementation that lacks the debug-stepper functionality in the swank server (Clozure CL). Unfortunately these functions produced exceptions, because in this case `s:DebugFrame()` returns the empty string and the swank_step_xxx() python functions complain because they are called without the frame parameter. As there is no point in doing anything for such lisp implementations, I'd suggest this kind of change for the `SlimvDebugStepXxx()` functions you added, e.g.:

```
function! SlimvDebugStepNext()
    let frame = s:DebugFrame()
    if frame != ''
        call SlimvDebugCommand( ":sldb-next", "swank_step_next", frame )
    endif
endfunction
```

Thanks again!

**Comment by kg7ski** [comment]
Tamas,

Thanks for your patience with me.  I have made the changes you suggested and I am pretty sure I have all the commits done correctly this time (at least when I do the compare they all show up).

cheers,

ski

**Comment by kovisoft** [comment]
Perfect! Thank you for the contribution!

**Pull request merged**
