### PR TITLE
Quick and dirty find-definitions-for-emacs

### PR DESCRIPTION
**Pull request by vi1**
_Very_ usefull slime's feature M-. -- jump to source definition for a symbol

Since swank:find-definitions-for-emacs returns a list of file locations I decided to create temporary tags file on the fly and use vim's builtin :tag command. Easy and convenient.

Dirty stuff. Hardcoded ~/tmp_tags for temporary tags file (and accordingly :set tags=~/tmp_tags in my .vimrc). Also hardcoded ,j to jump to source definition under symbol and ,J to prompt for a symbol to jump. I did not try to polish the patch, since I've never used python or vimscript and I don't know what is good style. The change is short, maybe you can turn it into a _proper_ fix.

Signed-off-by: vi ilya.vazhev@gmail.com

### CODE REVIEW

**Comment by scottbrown10** [comment]
Is there a problem with vi1's implementation? This would be a nice feature to have.

**Comment by kovisoft** [comment]
Uh, sorry, I decided to polish this pull request, but then I completely forgot about it.
Some problems I recall having noticed:
- collision of <leader>J with existing mapping for paredit join
- hardcoded tag file requiring additional changes in .vimrc
- temp file handling may not work on Windows (did not check that)

I'll try to address the above issues and create a proper fix.
Again, I'm terribly sorry, please forgive me.

**Comment by scottbrown10** [comment]
No problem. I know maintaining a library isn't easy. If you would like help refactoring/re-implementing, I'd be willing to try, as I just started learning vimscript the other day.

**Comment by vi1** [comment]
>Uh, sorry, I decided to polish this pull request, but then I completely forgot about it.

That's ok. It was not obviously a pull request, but rather an implementaion sketch. That I happily use since then though)

And thanks for Slimv, man!

j,J keys are solvable problem. The main problem is to (preferably silently) adjust vim tags settings.
Say have a variable slimv_temp_tags_file=~/blah-file
then in loading slimv, append or prepend it to tags.

To make it portable.

I use it on Windows, but I always set HOME. Clearly some users don's set HOME on Windows.

Is there any way in VimL to get a dir which it recognizes as "home"? From where it loads .vimrc. 
Vim has some logic to identify what is home dir. If HOME is set, it's clear. But if not, on Windows, it loads from HOMEPATH. But THEN does vim set some internal var to point to what was identified as home?
I guess there should be some var, but I can't find it. Then pass this dir+file to swank.py instead of 

open(os.environ['HOME']+'/tmp_tags', 'w')

**Comment by kovisoft** [comment]
j,J keys: my idea is to remap <Ctrl+]> (vim's default tag lookup), so that before jumping to a tag location it would call your SlimvFindDefinitionsForEmacs() function. This way we can use <leader>j for the prompt version (SlimvFindDefinitionsForEmacsPrompt) and leave <leader>J as it was.

Tags file: my idea is to use a tempfile generated by vim (using tempname() that works on all platforms). It would also be possible to define one dedicated tags file in .vimrc, but I'd not make it default, because using one tags file would mix/confuse the definitions among different projects.

**Comment by vi1** [comment]
>I'd be willing to try, as I just started learning vimscript the other day.

Sure, go ahead, man. I'm mostly a vim user, VimL is terra incongita for me.

**Comment by vi1** [comment]
>remap <Ctrl+]>
Sounds like a good idea.

>Tags file
I understood it like that - you call tempname(), save it for the "vim session" and prepend it to tags var. And will pass it to swank.py. Does tags var understand absolute windows names?

**Comment by kovisoft** [comment]
Tags file: yes, that's also how I meant it. The filename generated by tempname() is valid for the active vim session. The temp filename is appended at the end of the tags var, like in this (working) windows example:

`tags=./tags,./../tags,./../../tags,./*/tags,~\AppData\Local\Temp\VIA542C.tmp`

**Comment by vi1** [comment]
It's settled then, it's time to open a Champagne bottle.
And IMHO prepend is ok. If someone loads slimv he wants lisp in the first place.

**Comment by kovisoft** [comment]
OK, I agree, prepending is surely better, I'll do it accordingly.

**Comment by kovisoft** [comment]
I committed the polished version of your pull request, please see https://github.com/kovisoft/slimv/commit/7dc2109f4c09cb58479b5d3ad7cdcd21bbbe7fd8 . And sorry for the additional delay (I got sick in the meantime but recovered by now).

**Comment by vi1** [comment]
Thanks.

**Pull request closed without merging**
